### ISSUE TITLE
Feature - metrics over a batch

### ISSUE THREAD

**Issue by amirDahari1** [tldr-group/taufactor#31]
* TauFactor version: 0.1.3
* Python version: 3.8
* Operating System: Linux

For ease and faster computation in parallel - add a feature for a calculation over a batch of images. For example over a 4-dim array (N,D,H,W) for VF and SA that outputs an array of length N of the metric for each image.

**Comment by stke9** [comment]
This is an interesting option - the problem is, in most cases where it takes a significant amount of time to calculate any of these metrics, the volume is huge and memory would be an issue for batch solving. Equally, for small volumes the time saved by batch solving is negligible. I think for this reason it's probably unnecessary, but please do reopen this issue if i've missed a use case
