### ISSUE TITLE
Boundary conditions not being applied as expected

### ISSUE THREAD

**Issue by ma-sadeghi** [tldr-group/taufactor#45]
* TauFactor version: 0.1.4
* Python version: 3.9.13
* Operating System: Ubuntu 20.04

### Description

I tried to manually apply `bc=(1.1, 3.3)` as boundary conditions, but the solver doesn't seem to have applied them accordingly.

### What I Did

```python
import taufactor
import numpy as np
np.random.seed(0)
shape = [25, 25, 25]
im = np.random.rand(*shape) < 0.5
solver = taufactor.Solver(im, bc=(1.1, 3.3))
solver.solve()
print(solver.conc[:, :, 0].mean())
print(solver.conc[:, :, -1].mean())
print(solver.conc[:, 0, :].mean())
print(solver.conc[:, -1, :].mean())
print(solver.conc[0, :, :].mean())
print(solver.conc[-1, :, :].mean())
```

```
0.0
0.0
1.886145445545024
5.658436132229569
1.1668447369984039
1.1668447369984039
```

I was expecting to see 1.1 and 3.3 in the output (for two of the faces).

**Comment by ma-sadeghi** [comment]
My bad, I'm actually including the non-conductive voxels as 0s int he average, hence the incorrect averages.

Here's the corrected code:

```python
c = solver.conc.squeeze()[1:-1, 1:-1, 1:-1]
c[~im] = np.nan
print(np.nanmean(c[0, :, :]))
print(np.nanmean(c[-1, :, :]))
```

which produces:

```
1.117704033816446
3.289671806461918
```

which is very close the prescribed BCs. Is there a reason why I'm not getting exactly 1.1 and 3.3? Thanks!

**Comment by stke9** [comment]
Hi there,

sorry for the long wait! In your second comment code snippet, the first line actually cuts off the boundary condition (by taking 1:-1 in each direction). The mean values of conc you have found are for the layer next to the bc, hence they are very close but not exactly equal to the BCs. Worth noting that if you actually print the bc values using solver.conc, you will find they are twice the values you entered due to the way we set them up for solving. Hope this helps!
