### ISSUE TITLE
BUG for low porosity cubic volumes

### ISSUE THREAD

**Issue by isaacsquires** [tldr-group/taufactor#94]
* TauFactor version: 1.1.0
* Python version: 3.9
* Operating System: Ubuntu 20

### Description

Trying to get tau for low porosity cubes in cubes. Started not converging properly when porosity below 0.2. Noticed conv error jumping up and simulation ending after minimum number of iterations.

**Comment by amirDahari1** [comment]
Problem is negative flux causing err < 0 in `def check_vertical_flux(self, conv_crit):`

Possible fix 1:
Change the error from
`err = (fl.max() - fl.min())*2/(fl.max() + fl.min())`
into 
`err = (fl.max() - fl.min())*2/(fl.max())`
or `err = (fl.max() - fl.min())*2/(fl.max() + abs(fl.min()))`

Possible fix 2:
make the error an absolute one, i.e.
`err = abs((fl.max() - fl.min())*2/(fl.max() + fl.min()))`

I vote for the first option since if fl.max() ~= -fl.min() than the error can be really large or cause division by zero error in the extreme case that they're equal.

**Comment by amirDahari1** [comment]
#95 Possible fix
